# Generated by Django 4.2.17 on 2024-12-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0006_alter_category_created_by_alter_product_created_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="created_by",),
        migrations.RemoveField(model_name="product", name="created_by",),
    ]
